### PR TITLE
Make Scala Code More Idiomatic

### PR DESCRIPTION
**Pull request by omervk**
1. Add plugins for code formatting, linting, etc.
2. Canonicalize Scala code (remove `for`s, `return`s, mutable state, etc.)

(This is a rolling pull request)

### CODE REVIEW

**Comment by jornfranke** [comment]
hmm there a re conflicting files, can you please check? maybe it was because i merged your other pull request before? sorry about this...

**Comment by omervk** [comment]
No worries. I know there were conflicts but I'm not yet finished. Will ping you when I am so you can review :)

**Comment by omervk** [comment]
@jornfranke it seems like asking for Spark 1.5 in compile and 2.0 in tests breaks IntelliJ IDEA's plugin. how about we just skip ahead to 2.0+ support only while we're at it?

Also recommend running integration tests against every minor version of Spark (2.0, 2.1, 2.2) because of backwards compatibility issues (like the one reported by @liorregev).

**Comment by jornfranke** [comment]
Ok sounds fine.

I will check the merge later.

**Comment by omervk** [comment]
@jornfranke Why was this merged? I wasn't finished working on it...

**Comment by jornfranke** [comment]
Sorry i thought it was finished. Please create another one and it will be included

**Comment by omervk** [comment]
Sure, I'll create a new pull request once I'm done :)

**Comment by jornfranke** [comment]
Ok thx do not forget to update the issue with what is still open (a short comment is fine) - thank you a lot

**Pull request merged**
