### PR TITLE
Make Tests More Readable and Maintainable

### PR DESCRIPTION
**Pull request by omervk**
1. Tests are now typed.
2. Expected data is more readable.
3. No need to involve Hadoop, since Spark knows how to read from the file system.
4. I changed the types in the dataset to be Seq[Byte] instead of Array[Byte] since comparisons are not natively implemented for Arrays (they are compared by reference, rather than by value). This means that all comparison is now done by ScalaTest out of the box.

@jornfranke, I know you asked not to remove the existing tests, but these exactly duplicate the tests you had...

Note: I tried to load the namecoin transactions as transactions and only got the first one. Bug?

### CODE REVIEW

**Comment by jornfranke** [comment]
In fact I would be happy if you have contacted before, because many people use Hadoop with Spark and this I would prefer the tests to be there. Can’t we have both at the same time? We cannot arbitrarily change test cases because if they are not comparable they are useless.

We have to keep in mind that also other people are using it and we cannot continue to introduce breaking changes...


Namecoin - i do not know i could give you an answer if the test cases would have stayed the change. I need more time. 

As a Proposal: please restore the old test cases and add new ones if you think they are needed. I think the new test cases are good, but we need to really keep in mind that it not only purposes one person, but several ones.

**Comment by omervk** [comment]
Hi @jornfranke, sorry for not getting back to you until now. Due to some internal changes, I'm not going to be able to spend as much time as I'd like making pull requests into this repo. Since this change is not big and/or breaking I am letting myself drop it. If you'd like, you can pick it up and I'll be happy to explain it, but I'm not sure it's a good return on investment at this point...

**Comment by jornfranke** [comment]
I will check I think I got the idea and will add your proposed change as a second test class.

**Comment by jornfranke** [comment]
i will revisit it later

**Pull request closed without merging**
