### PR TITLE
Add Current hash in block BitcoinBlockRelation

### PR DESCRIPTION
**Pull request by ghost**
I'm using `spark-hadoopcryptoledger-ds` in Spark DataFrames, so I'm doing this:

`val df = spark.read.format("org.zuinnote.spark.bitcoin.block").option("magic", "F9BEB4D9").load("gs://bitcoinstorage/blk00*.dat")`

The problem is that I cannot calculate current transaction hash easily. I have to create complex UDF to do that. Adding `currentTransactionHash` will have greatly to have easy interface to interact with bitcoin data using dataframes.

### CODE REVIEW

**Comment by jornfranke** [comment]
Thanks. You can alternatively use the transaction format which has it already inside.
Additionally BitcoinUtil has it, but we can add it also to the BitcoinBlock format.

**Comment by jornfranke** [comment]
Let me check the pull request later i will probably make it configurable (enrich) so the users have the choice of they want to calculate it or not.

**Comment by ghost** [comment]
@jornfranke awesome, thank you!

**Comment by jornfranke** [comment]
Hi,

I added the transactionHash. The code that is provided as part of the pull request could not be used directly, because you add the line rowArray(10) which overrides other information and does not pass the automated tests.
Additionally I made the calculation of the transaction hash configurable via the enrich information. 

Hence, I added the code necessary for it myself and added also integration tests to see (cf. also [Contributing](https://github.com/ZuInnoTe/spark-hadoopcryptoledger-ds/blob/master/CONTRIBUTING.md)). Please let me know if this is acceptable by you and if i can close the pull request.

I can release this maybe end of next week as version 1.1.1

All the best

**Comment by ghost** [comment]
@jornfranke 

that really helps, thank you a lot.

> I can release this maybe end of next week as version 1.1.1

awesome! thanks for amazing project.

**Pull request closed without merging**
