### PR TITLE
General Improvements

### PR DESCRIPTION
**Pull request by omervk**
Continuing the work started in ZuInnoTe/spark-hadoopcryptoledger-ds#13.

Includes, but not limited to:

1. Conversions from Hadoop's Java classes to Spark's case classes.
2. Removal of most manual code from relation classes.
3. Move to Spark 2+.
4. Integration tests now run against all supported minor versions of Spark.
5. Some initial work on tests.

### CODE REVIEW

**Comment by omervk** [comment]
@jornfranke This pull request is ready. Both failing checks are false positives. Looking forward to your review :)

**Comment by jornfranke** [comment]
Great thx a lot. This will be a very valuable contribution.

We should make sure that the DS does not break compatibility with the current one.

**Comment by omervk** [comment]
I don't think there's a need for that, since the unit tests cover the entire structure of the data.

I didn't code the case classes by hand, but instead wrote a script that converts StructTypes to case class hierarchies, so manual mistakes are going to be much rarer.

**Comment by omervk** [comment]
Also, I'd like to change the unit tests to be more concise and to use the types instead of attempting to read data from the dataframe. The dataframe is still there and can be read untyped by definition, but the tests would benefit since they would be more readable and adding new ones would be easier.

wdyt?

**Comment by jornfranke** [comment]
Hmm can you create please a new test class for it? I am reluctant to change existing tests because unit tests should be repeatable and only change if there is a bug in the test cases.

Thank you!

**Comment by omervk** [comment]
Sure thing. I'll create a new pull request for that.

**Comment by jornfranke** [comment]
Great thank you a lot, very good work

**Comment by omervk** [comment]
No worries. Let me know if there are any issues with this one before merging it. 👍

**Comment by jornfranke** [comment]
it looks very good.  thank you a lot.

Just one question about the version, could we use 1.1.3 instead of 1.2.0?
I try to somehow link the hadoopcryptoledger version to be equal to the spark-hadoopcrypto-ledger version and we could update both to 1.1.3.

In the past I used major versions for new blockchain formats (e.g. 1.0.X was Bitcoin, 1.1.X was Ethereum , 1.2.X will ??). I admit I never wrote this down.

**Comment by omervk** [comment]
I try to use semantic versioning for all of the projects I'm involved in
and try not to couple versions of different products, but I'm not going to
press the matter here. You're welcome to make the edit and merge since I'm
not near a computer at the moment...

**Comment by jornfranke** [comment]
I agree with you. However, I want to avoid tables where I say you have to use this Spark datasource version with this version of the HadoopCryptoLedger library etc.

I will check later to update it.

I can though release it on Maven Central etc. only later this week, maybe weekend.

**Comment by jornfranke** [comment]
lets leave it with version 1.2.0, I will put it for the hadoopcryptoledger library as well there.

**Comment by jornfranke** [comment]
I receive some errors when compiling for scala 2.10 (implicit widening...). I will check it tomorrow.

I added also you as author information for the new files and included the Apache license for them.

**Comment by omervk** [comment]
I recommend a quick release of 1.2.0 because master is pretty far from 1.1.2 now :)

**Comment by jornfranke** [comment]
Ok this week

**Comment by jornfranke** [comment]
We also need to fix the scala 2.10 compilation error (see above).

**Comment by omervk** [comment]
Could you open it as an additional issue and I'll create a pull request for it?

**Comment by omervk** [comment]
Fixed in ZuInnoTe/spark-hadoopcryptoledger-ds#15

**Comment by jornfranke** [comment]
Just to avoid misunderstandings : the improvements are good, but it would be good to keep the Hadoop integration tests. We can add any non Hadoop integration tests as we want. 
About the namecoin - in previous test cases it worked without issues. Maybe you forgot to activate auxpow.

**Pull request merged**
