### PR TITLE
Add Types for Data

### PR DESCRIPTION
**Pull request by omervk**
This is for ZuInnoTe/spark-hadoopcryptoledger-ds#10

### CODE REVIEW

**Comment by omervk** [comment]
@jornfranke I'm not sure how to fix the issue the automated build is facing.

**Comment by omervk** [comment]
A couple more notes while I'm here:

1. I created a type per permutation of options (BitcoinBlock, EnrichedBitcoinBlock, BitcoinBlockWithAuxPOW, etc.), rather than having the extra data as Option[T], because I wanted the types to accurately describe what data exists and make sure it exists when converting the dataframe to the dataset. Fail early, et al.
2. I refrained from converting the Array[Byte] data to anything else (with helper methods on the new types) because that would require a lot more logic and should be contained in a different issue, if needed.
3. I would love to help canonicalize the Scala code if @jornfranke would agree. Some of the code in the repository is not idiomatic and reading it is not intuitive for Scala coders. Your call, Jörn :)

**Comment by jornfranke** [comment]
I will check the issue with the build later.
1. is fine
2. originally this was on purpose to have access to the raw data without costly conversion routines so you can do what it want. I agree that an additional enriched layer can make sense.
3. I agree with you. Can you please create another issue - maybe propose some formatting rules or an IDE functionality that we can use. Then I can help as well.

Thank you a lot.

**Comment by jornfranke** [comment]
ok it is fine, i think the issue with the token is not related to the PR itself, it will in version 1.1.3

**Pull request merged**
